bmi-era5:
  name: reanalysis-era5-single-levels-monthly-means
  request:
    variable:
      - 2m_temperature
      - snow_density
      - snow_depth
    product_type: monthly_averaged_reanalysis
    year: 
      - '1980'
      - '1981'
      - '1982'
      - '1983'
      - '1984'
      - '1985'
      - '1986'
      - '1987'
      - '1988'
      - '1989'

    month:
      - '01'
      - '02' 
      - '03'
      - '04'
      - '05'
      - '06'
      - '07'
      - '08'
      - '09'
      - '10'
      - '11'
      - '12'
    time:
      - '00:00'
    format: netcdf
    area:
      - 63.92
      - -149.30
      - 63.67
      - -149.05
    grid:
      - 0.25
      - 0.25
  path: './cache_alaska/era5_1980.nc'

