name: permafrost_usecase
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pymt=1.3.1
  - cdsapi
  - pymt_topography
  - pymt_era5
  - numpy=1.23.5
  - xarray
  - cftime
  - imageio
  - imageio-ffmpeg
  - matplotlib
  - jupyter
  - tqdm
